import { Link } from 'react-router-dom';
import type { ReactNode } from 'react';
import { Badge } from '../../../components/ui/Badge';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { Spinner } from '../../../components/ui/Spinner';
import type {
  AiArticleReference,
  AiMode,
  Ticket,
  TicketPriority,
} from '../../../types/api';
import { aiErrorMessages } from '../aiFailure';
import {
  useAiDraftResponse,
  useAiResolutionSummary,
  useAiStatus,
  useAiTriage,
} from '../useAi';

const LINK_CLASSES =
  'font-medium text-slate-900 underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-slate-900';

/**
 * Shown above every block of generated text. ADR-023 Decision 7 names
 * labelling AI output as part of this feature's prompt-injection mitigation,
 * not as presentation: a crafted ticket can still bias the wording of a draft
 * or the choice among legitimate categories, and the thing that makes that
 * acceptable is a human knowing they are reading a machine's guess before they
 * act on it.
 */
const REVIEW_NOTICE =
  'Generated by AI from this ticket. Check it before you act on it.';

/**
 * Said plainly whenever the server is in mock mode. ADR-023 Decision 3 keeps
 * "disabled" and "mock" as two different things precisely so that canned
 * output is never presented as a model's analysis; hiding the distinction in
 * the UI would give back exactly what that decision bought.
 */
const MOCK_NOTICE =
  'This server is in demonstration mode: the text below is canned sample output, not a model’s analysis.';

/**
 * The same disclosure, attached to one result.
 *
 * The panel-level notice above is derived from the cached `GET /ai/status`,
 * which has a five-minute `staleTime` and is not refetched on focus — so a
 * provider change on the server can leave the cached status saying `anthropic`
 * while a response actually carries `mode: 'mock'`. Every result payload
 * carries its own `mode` for exactly this reason, and a result labels itself
 * from that rather than from the cached configuration. Without this, canned
 * category and priority advice could render with no demonstration-mode label
 * at all, which is the outcome ADR-023 Decision 3 exists to prevent.
 */
const MOCK_RESULT_NOTICE =
  'Canned sample output — this server is in demonstration mode.';

export interface TicketAiAssistantPanelProps {
  ticket: Ticket;
  /**
   * Applying a suggestion is an ordinary ticket update, so it is owned by the
   * ticket page and merely invoked from here. That keeps every ticket mutation
   * — and its 403/409 recovery — in one place, and keeps this feature free of
   * any code path that can change a ticket.
   */
  onApplyCategory: (categoryId: string) => void;
  onApplyPriority: (priority: TicketPriority) => void;
  /** True while any ticket update is in flight, from either button. */
  applying: boolean;
}

/**
 * The staff-facing AI assistant on the ticket detail page.
 *
 * Three independent, human-triggered actions: triage (category, priority and
 * related reading), a draft reply to the requester, and a resolution summary.
 * Nothing here changes the ticket. Suggestions are rendered as suggestions,
 * and the only way one takes effect is a second, explicit click on Apply,
 * which goes through the ordinary ticket update API (ADR-023 Decision 5).
 */
export function TicketAiAssistantPanel({
  ticket,
  onApplyCategory,
  onApplyPriority,
  applying,
}: TicketAiAssistantPanelProps) {
  const statusQuery = useAiStatus();
  const triage = useAiTriage(ticket.id);
  const draft = useAiDraftResponse(ticket.id);
  const summary = useAiResolutionSummary(ticket.id);

  /*
   * One in-flight call at a time across all three buttons. The backend caps
   * concurrent AI work at five in-process and answers `busy` beyond it, so
   * letting one person queue three at once would mostly serve them their own
   * rate limit. It also keeps the single live region below unambiguous.
   */
  const running = triage.isPending || draft.isPending || summary.isPending;

  if (statusQuery.isPending) {
    return (
      <AssistantCard>
        <Spinner label="Checking whether the AI assistant is available" />
      </AssistantCard>
    );
  }

  /*
   * Fails closed, and quietly. `enabled: false` is the DEFAULT state of this
   * application — it ships with no provider configured (ADR-023 Decision 3) —
   * so it is ordinary configuration, not an error, and must not raise a red
   * alert on a ticket page. A failed status request is folded into the same
   * branch deliberately: in both cases the honest thing to tell a support
   * agent is that the optional helper is not available right now, and in
   * neither case may a button be offered that could only fail.
   */
  if (statusQuery.isError || !statusQuery.data?.enabled) {
    return (
      <AssistantCard>
        <p className="text-sm text-slate-600">
          The AI assistant is not available on this server.
        </p>
      </AssistantCard>
    );
  }

  const { mode } = statusQuery.data;

  return (
    <AssistantCard mode={mode}>
      <p className="text-sm text-slate-600">
        Suggestions only. Nothing here changes the ticket until you apply it.
      </p>

      {mode === 'mock' ? (
        <p className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">
          {MOCK_NOTICE}
        </p>
      ) : null}

      <div className="flex flex-wrap gap-2">
        <Button
          variant="secondary"
          disabled={running}
          onClick={() => triage.mutate()}
        >
          Suggest triage
        </Button>
        <Button
          variant="secondary"
          disabled={running}
          onClick={() => draft.mutate()}
        >
          Draft a response
        </Button>
        <Button
          variant="secondary"
          disabled={running}
          onClick={() => summary.mutate()}
        >
          Summarise resolution
        </Button>
      </div>

      {/*
        Mounted unconditionally and its contents swapped — a live region
        inserted into the DOM with its text already in place is not reliably
        announced (the same rationale documented in `TicketDetailPage`).
      */}
      <div aria-live="polite" className="flex flex-col gap-4">
        {running ? <Spinner label="Asking the AI assistant" /> : null}

        <ResultBlock
          heading="Suggested triage"
          error={triage.error}
          show={triage.isSuccess && !triage.isPending}
          resultMode={triage.data?.mode}
        >
          {triage.data ? (
            <TriageResult
              data={triage.data}
              ticket={ticket}
              applying={applying || running}
              onApplyCategory={onApplyCategory}
              onApplyPriority={onApplyPriority}
            />
          ) : null}
        </ResultBlock>

        <ResultBlock
          heading="Draft response"
          error={draft.error}
          show={draft.isSuccess && !draft.isPending}
          resultMode={draft.data?.mode}
        >
          {draft.data ? (
            <>
              <p className="text-sm text-slate-600">
                Not sent and not posted. Copy it into a comment if you want to
                use it.
              </p>
              {/*
                Read-only rather than a live composer: a draft is written to be
                sent to the requester, so it must pass through a person's hands
                and the comment form's own validation, never slide into a
                submit by itself.
              */}
              <label
                className="text-sm font-medium text-slate-900"
                htmlFor="ai-draft-response"
              >
                Draft reply to the requester
              </label>
              <textarea
                id="ai-draft-response"
                readOnly
                rows={8}
                value={draft.data.draft}
                className="user-content w-full rounded-md border border-slate-300 bg-slate-50 p-2 text-sm text-slate-800"
              />
              <ArticleReferences
                heading="Articles this draft drew on"
                articles={draft.data.referencedArticles}
              />
            </>
          ) : null}
        </ResultBlock>

        <ResultBlock
          heading="Resolution summary"
          error={summary.error}
          show={summary.isSuccess && !summary.isPending}
          resultMode={summary.data?.mode}
        >
          {summary.data ? (
            <p className="user-content text-sm text-slate-800">
              {summary.data.summary}
            </p>
          ) : null}
        </ResultBlock>
      </div>
    </AssistantCard>
  );
}

function AssistantCard({
  children,
  mode,
}: {
  children: ReactNode;
  mode?: AiMode;
}) {
  return (
    <Card
      heading="AI assistant"
      // The badge's text carries the whole meaning; the tone is redundant.
      actions={
        mode === 'mock' ? (
          <Badge tone="warning" srPrefix="Mode:">
            Demonstration mode
          </Badge>
        ) : undefined
      }
    >
      <div className="flex flex-col gap-3">{children}</div>
    </Card>
  );
}

/**
 * One task's outcome: its failure, or its result under the standing review
 * notice. A failure renders through `aiErrorMessages`, which turns the
 * assistant's `AI_UNAVAILABLE` 503 into copy that says whether retrying is
 * worth it, and leaves every other failure reading exactly as it does
 * elsewhere in the application.
 */
function ResultBlock({
  heading,
  error,
  show,
  resultMode,
  children,
}: {
  heading: string;
  error: unknown;
  show: boolean;
  /** This result's OWN mode, not the cached server status — see
   * `MOCK_RESULT_NOTICE`. */
  resultMode?: AiMode;
  children: ReactNode;
}) {
  if (error) {
    return (
      <div className="rounded-md border border-red-300 bg-red-50 p-3">
        <p className="text-sm font-semibold text-red-900">
          {heading} unavailable
        </p>
        {aiErrorMessages(error).map((message) => (
          <p key={message} className="mt-1 text-sm text-red-900">
            {message}
          </p>
        ))}
      </div>
    );
  }

  if (!show) {
    return null;
  }

  return (
    <div className="flex flex-col gap-2 rounded-md border border-slate-200 bg-slate-50 p-3">
      <h3 className="text-sm font-semibold text-slate-900">{heading}</h3>
      <p className="text-xs font-medium text-slate-600">{REVIEW_NOTICE}</p>
      {resultMode === 'mock' ? (
        <p className="text-xs font-medium text-amber-900">
          {MOCK_RESULT_NOTICE}
        </p>
      ) : null}
      {children}
    </div>
  );
}

function TriageResult({
  data,
  ticket,
  applying,
  onApplyCategory,
  onApplyPriority,
}: {
  data: {
    suggestedCategory: { id: string; name: string } | null;
    suggestedPriority: TicketPriority | null;
    rationale: string | null;
    relatedArticles: AiArticleReference[];
  };
  ticket: Ticket;
  applying: boolean;
  onApplyCategory: (categoryId: string) => void;
  onApplyPriority: (priority: TicketPriority) => void;
}) {
  const { suggestedCategory, suggestedPriority, rationale, relatedArticles } =
    data;

  const nothingSuggested =
    !suggestedCategory &&
    !suggestedPriority &&
    !rationale &&
    relatedArticles.length === 0;

  if (nothingSuggested) {
    // A 200 with every field dropped is a real outcome, not an error: each
    // field is grounded independently and any of them can fail validation.
    return (
      <p className="text-sm text-slate-600">
        The assistant had no usable suggestion for this ticket.
      </p>
    );
  }

  const categoryAlreadySet = suggestedCategory?.id === ticket.category?.id;
  const priorityAlreadySet = suggestedPriority === ticket.priority;

  return (
    <div className="flex flex-col gap-3 text-sm">
      {suggestedCategory ? (
        <div className="flex flex-wrap items-center gap-2">
          <span className="font-medium text-slate-700">Category</span>
          <span className="text-slate-800">{suggestedCategory.name}</span>
          {categoryAlreadySet ? (
            <span className="text-slate-600">— already set</span>
          ) : (
            <Button
              variant="secondary"
              disabled={applying}
              onClick={() => onApplyCategory(suggestedCategory.id)}
            >
              Apply category
            </Button>
          )}
        </div>
      ) : null}

      {suggestedPriority ? (
        <div className="flex flex-wrap items-center gap-2">
          <span className="font-medium text-slate-700">Priority</span>
          <span className="text-slate-800">{suggestedPriority}</span>
          {priorityAlreadySet ? (
            <span className="text-slate-600">— already set</span>
          ) : (
            <Button
              variant="secondary"
              disabled={applying}
              onClick={() => onApplyPriority(suggestedPriority)}
            >
              Apply priority
            </Button>
          )}
        </div>
      ) : null}

      {rationale ? (
        <div>
          <p className="font-medium text-slate-700">Rationale</p>
          {/* Model text, rendered as a text node like every other piece of
              untrusted content in this application. */}
          <p className="user-content mt-1 text-slate-800">{rationale}</p>
        </div>
      ) : null}

      <ArticleReferences
        heading="Related knowledge articles"
        articles={relatedArticles}
      />
    </div>
  );
}

/**
 * Article links are safe to render for anyone who was served them: the backend
 * assembles the candidate set under the caller's own visibility rule and
 * re-reads each row under that rule before responding, so a link here cannot
 * hand someone an article they may not open.
 */
function ArticleReferences({
  heading,
  articles,
}: {
  heading: string;
  articles: AiArticleReference[];
}) {
  if (articles.length === 0) {
    return null;
  }

  return (
    <div>
      <p className="text-sm font-medium text-slate-700">{heading}</p>
      <ul className="mt-1 flex flex-col gap-1">
        {articles.map((article) => (
          <li key={article.id} className="text-sm">
            <Link to={`/kb/${article.id}`} className={LINK_CLASSES}>
              {article.title}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}
